repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: detect-aws-credentials
        args: [--credentials-file=./.aws/credentials]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      # language_version: python3.9  # do not include, since it works with multiple python versions
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8